# This is a basic workflow to help you get started with Actions

name: Processing

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Download & Install Processing
        run: | 
          sudo curl -L -o /opt/processing-3.5.4-linux64.tgz https://download.processing.org/processing-3.5.4-linux64.tgz
          sudo tar zxvf /opt/processing-3.5.4-linux64.tgz -C /opt/
        
      - name: Build the Project
        run: |
          ls /opt/
          ls /opt/processing-3.5.4/
          /opt/processing-3.5.4/processing-java --sketch="$PWD"/main --build
          
